{% set name = "robyn" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: 74dc0246cc6a673056379ef7bc7d4ed394849a8e3e6c0902904ae17dcaee5be5
  patches:
    - 0001-add-maturin.patch

build:
  skip: true  # [py<38]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin

  host:
    - maturin
    - poetry
    - pip
    - python
    - rust
  run:
    - multiprocess ==0.70.12.2
    - python
    - requests ==2.26.0
    - uvloop ==0.16.0  # [unix]
    - watchdog >=2.1.3

test:
  imports:
    - robyn
  commands:
    - pytest -vvv --capture=tee-sys integration_tests
  source_files:
    - integration_tests
  requires:
    - pytest
    - pytest-sugar
    - websockets

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
