{% set name = "robyn" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: befbe66f9186009ca3f59643bf092d1b0f2c11c0fad50ca25ad7b6216e2401e8
  patches:
    - 0001-add-maturin.patch

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin

  host:
    - maturin
    - poetry
    - pip
    - python
    - rust
  run:
    - python
    - watchdog >=2.1.3,<3

test:
  imports:
    - robyn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
