{% set name = "robyn" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: f53c2cd9e862a32a33e43ce45d45b5249c9e2a3cd7be90094820d1b006731a16

build:
  skip: true  # [py<38 or python_impl == 'pypy' or py>311]
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robyn=robyn.cli:run

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    # upstream uses maturin >=0.12,<0.13, but on conda maturin 0.12 not available for python 3.11, loosening requirements here
    - maturin >=0.12,<0.13  # [py<311]
    - maturin >=0.12  # [py>=311]
    - pip
    - python
  run:
    - python
    - watchdog ==4.0.1
    - multiprocess ==0.70.14
    - nestd ==0.3.1
    - inquirerpy ==0.3.4
    - uvloop ~=0.19.0  # [unix]
    - rustimport ==1.3.4
    - orjson ==3.9.15
test:
  imports:
    - robyn
  commands:
    - pip check
    - robyn --help
  requires:
    - pip

about:
  home: https://robyn.tech/
  dev_url: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
