{% set name = "robyn" %}
{% set version = "0.52.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: f4f30bbc6364f724e40fd1280d0c42ec6ee62af0335d2fa622c5250d12ddce27

build:
  skip: true  # [py<38 or python_impl == 'pypy']
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    # upstream uses maturin >=0.12,<0.13, but on conda maturin 0.12 not available for python 3.11, loosening requirements here
    - maturin >=0.12,<0.13  # [py<311]
    - maturin >=0.12  # [py>=311]
    - pip
    - python
  run:
    - python
    - watchdog ==2.2.1
    - multiprocess ==0.70.14
    - nestd ==0.3.1
    - inquirerpy ==0.3.4
    - uvloop ~=0.19.0  # [unix]
    - rustimport >=1.3.4<2.0.0
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
test:
  source_files:
    - integration_tests
  imports:
    - robyn
  commands:
    - pip check
  #   - pytest -vvv --capture=tee-sys --pyargs robyn
  requires:
    - pip
  #   - jinja2
  #   - pytest ==7.2.1
  #   - websocket-client ==1.5.0
  #   - requests ==2.28.2

about:
  home: https://robyn.tech/
  dev_url: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
