{% set name = "robyn" %}
{% set version = "0.16.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: 5e6ee3b8b047f4707f10200a75cbf15e5c1d8b981a22cc71abe2d5111c642f98

build:
  skip: true  # [py<37]
  number: 0
  script:
    # TODO remove this when rust-activation-feedstock is fixed
    - export CARGO_BUILD_RUSTFLAGS="$CARGO_BUILD_RUSTFLAGS -C link-arg=-Wl,-headerpad_max_install_names -C link-arg=-Wl,-dead_strip_dylibs"  # [osx]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=0.12,<0.13
    - pip
    - python
  run:
    - multiprocess ==0.70.12.2
    - python
    - requests ==2.26.0
    - uvloop ==0.16.0  # [unix]
    - watchdog >=2.1.3

test:
  imports:
    - robyn
  commands:
    - pytest -vvv --capture=tee-sys integration_tests  # [not win]
  source_files:
    - integration_tests
  requires:
    - pytest==6.2.5
    - websockets

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
