{% set name = "robyn" %}
{% set version = "0.49.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: 93e34b6369a32b457e80a2561ec13433cabb3bb2ea776dd95935ebb8f9ebf922

build:
  skip: true  # [py<38 or python_impl == 'pypy']
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=0.12
    - pip
    - python
  run:
    - inquirerpy ==0.3.4
    - multiprocess ==0.70.14
    - nestd ==0.3.1
    - python
    - uvloop ~=0.17.0  # [unix]
    - watchdog ==2.2.1

test:
  source_files:
    - integration_tests
  imports:
    - robyn
  # commands:
  #   - pytest -vvv --capture=tee-sys --pyargs robyn
  # requires:
  #   - jinja2
  #   - pytest ==7.2.1
  #   - websocket-client ==1.5.0
  #   - requests ==2.28.2

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
