{% set name = "robyn" %}
{% set version = "0.19.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: f401dd8d69df4e9145fe586adc4930d6e0c888637b97d4a27296bc20b395c286

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=0.12,<0.13
    - pip
    - python
  run:
    - multiprocess ==0.70.12.2
    - python
    - pytest ==6.2.5
    - requests ==2.26.0
    - uvloop ==0.16.0  # [unix]
    - watchdog >=2.1.3

test:
  imports:
    - robyn

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
