{% set name = "robyn" %}
{% set version = "0.41.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: f5e656e043e02925a528b9aa47ac7e034768419430d94264738f7fc982ce6411

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=0.12,<0.13
    - pip
    - python
  run:
    - inquirerpy ==0.3.4
    - multiprocess ==0.70.14
    - nestd ==0.3.1
    - python
    - uvloop ==0.17.0  # [unix]
    - watchdog ==2.2.1

test:
  source_files:
    - integration_tests
  imports:
    - robyn
  commands:
    - pytest -vvv --capture=tee-sys  integration_tests
  requires:
    - jinja2
    - pytest
    - websocket-client ==1.5.0
    - requests ==2.28.2

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
