{% set name = "robyn" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robyn-{{ version }}.tar.gz
  sha256: 5be55fc0476f2e0154c29be08b05076838aca19447602afb57628222bbcaf5fa
  patches:
    - 0001-add-maturin.patch

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin

  host:
    - maturin
    - poetry
    - pip
    - python
    - rust
  run:
    - multiprocess ==0.70.12.2
    - python
    - requests ==2.26.0
    - uvloop ==0.16.0  # [unix]
    - watchdog ==2.1.3

test:
  imports:
    - robyn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sansyrox/robyn
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
