schema_version: 1

context:
  name: robyn
  version: 0.68.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/robyn-${{ version }}.tar.gz
  sha256: 7225b388fe2e911f35724bb941636302bfa8a0c12e4bdb6c8fc171434702cbf4

build:
  number: 0
  skip: match(python, "<3.8") or python_impl == 'pypy' or match(python, ">3.11")
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - robyn=robyn.cli:run

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    # upstream uses maturin >=0.12,<0.13, but on conda maturin 0.12 not available for python 3.11, loosening requirements here
    - if: match(python, "<3.11")
      then: maturin >=0.12,<0.13
    - if: match(python, ">=3.11")
      then: maturin >=0.12
    - pip
    - python
  run:
    - python
    - inquirerpy ==0.3.4
    - multiprocess ==0.70.14
    - orjson ==3.9.15
    - rustimport ==1.3.4
    - if: unix
      then: uvloop ~=0.21.0
    - watchdog ==4.0.1

tests:
  - python:
      imports:
        - robyn
      pip_check: true
  - requirements:
      run:
        - python
    script:
      - robyn --help

about:
  summary: Async Python backend server with a runtime written in Rust.
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://robyn.tech/
  repository: https://github.com/sansyrox/robyn
  documentation: https://sansyrox.github.io/robyn/

extra:
  recipe-maintainers:
    - thewchan
